name: Validate JSON Schema
on:
  pull_request:
    paths:
    - 'jsonschema/workflows.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: workflows-samples > Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install tools
        run: npm install -g ajv-cli ajv-formats

      - name: Validate workflow
        run: ajv compile -c ajv-formats -s jsonschema/workflows.json

      - name: workflows-demos > Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          repository: GoogleCloudPlatform/workflows-demos
          path: workflows-demos

      - name: Validate cheatsheet
        run: |
          ajv validate -c ajv-formats \
            -s jsonschema/workflows.json \
            -d workflows-demos/syntax-cheat-sheet/workflow.yaml

